#!/usr/bin/env python3
# CSTPSI -- Composable Set-Threshold Labeled PSI
# Author: Erkam Uzun
# Copyright (c) 2026 Erkam Uzun. PolyForm Noncommercial License 1.0.0.
#
"""
render_table.py -- render the head-to-head performance table from measured
per-cell results (the output of summarize.py).

Per-query online time  = total_online_ms / (n_tp + n_tn) / 1000   [seconds]
Per-query communication = net_total_bytes / (n_tp + n_tn) / 2^20  [MiB]
Both definitions are applied identically to STLPSI and CSTPSI, so the speedup
(STL/CST) and the communication saving ((STL-CST)/STL) are apples-to-apples.

The garbled circuit runs once per session in CSTPSI and once per round in
STLPSI; dividing the session total by the query count amortizes that one-time
cost the same way for both modes. Absolute timing is hardware-dependent; the
reproduced claims are the speedup ratio, the communication saving, and FRR/FAR.

Usage:
  python3 render_table.py --summary <repro_summary.csv> [--tex out.tex]
"""
import argparse, csv, io, sys

D_ORDER  = ["1k", "10k", "100k", "1m"]
D_DISP   = {"1k": "1K", "10k": "10K", "100k": "100K", "1m": "1M"}
L_ORDER  = ["23bit", "16byte", "32byte", "64byte"]
L_DISP   = {"23bit": "23-bit", "16byte": "16-B", "32byte": "32-B", "64byte": "64-B"}
THREADS  = [1, 4, 8]


def load(path):
    txt = [ln for ln in open(path) if not ln.startswith("#")]
    return list(csv.DictReader(io.StringIO("".join(txt))))


def fmt_t(x):
    return f"{x:.2f}" if x < 1 else f"{x:.1f}"


def fmt_c(x):
    return f"{x:.1f}" if x < 10 else f"{x:.0f}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--summary", required=True)
    ap.add_argument("--tex")
    ap.add_argument("--md")
    args = ap.parse_args()

    cell = {}  # (db_label, label, threads, mode) -> (time_s, comm_mib)
    for r in load(args.summary):
        try:
            nq = int(r["n_tp"]) + int(r["n_tn"])
            if nq == 0:
                continue
            t = float(r["total_online_ms"]) / nq / 1000.0
            c = float(r["net_total_bytes"]) / nq / 1048576.0
            cell[(r["db_label"], r["label"], int(r["threads"]), r["mode"])] = (t, c)
        except (KeyError, ValueError):
            continue

    present_D = [d for d in D_ORDER if any(k[0] == d for k in cell)]
    present_L = [l for l in L_ORDER if any(k[1] == l for k in cell)]
    present_T = [t for t in THREADS if any(k[2] == t for k in cell)]
    if not present_D:
        print("render_table: no usable rows in summary.", file=sys.stderr)
        sys.exit(1)

    # ---- plain text ----
    hdr = f"{'D':>5} {'Label':>7} |"
    for t in present_T:
        hdr += f"  {f'{t}T STL':>7} {'CST':>7} {'Spd':>5} |"
    hdr += f"  {'cSTL':>6} {'cCST':>6} {'Save':>5}   (time s, comm MiB)"
    print(hdr); print("-" * len(hdr))
    for d in present_D:
        for l in present_L:
            line = f"{D_DISP[d]:>5} {L_DISP[l]:>7} |"
            comm = None
            for t in present_T:
                s = cell.get((d, l, t, "STLPSI")); c = cell.get((d, l, t, "CSTPSI"))
                if s and c:
                    spd = s[0] / c[0] if c[0] else 0.0
                    line += f"  {fmt_t(s[0]):>7} {fmt_t(c[0]):>7} {spd:>4.1f}x |"
                    comm = (s[1], c[1])
                else:
                    line += f"  {'-':>7} {'-':>7} {'-':>5} |"
            if comm:
                save = (comm[0] - comm[1]) / comm[0] * 100 if comm[0] else 0.0
                sv = f"{save:.0f}%" if save >= 0 else "-"
                line += f"  {fmt_c(comm[0]):>6} {fmt_c(comm[1]):>6} {sv:>5}"
            print(line)

    # ---- LaTeX ----
    if args.tex:
        def b(x, win): return f"\\textbf{{{x}}}" if win else x
        L = []
        L.append("% auto-generated by render_table.py -- measured head-to-head table")
        L.append("\\begin{table*}[t]\\centering")
        L.append("\\caption{Per-query online time (s) and communication (MiB), measured. "
                 "Faster time and lower communication are bolded; ``Save'' is CSTPSI's "
                 "communication saving (``-'' = CSTPSI sends more).}")
        L.append("\\small\\setlength{\\tabcolsep}{4pt}")
        cols = "ll" + " ccc" * len(present_T) + " ccc"
        L.append("\\begin{tabular}{%s}" % cols)
        L.append("\\toprule")
        top = "& "
        for t in present_T:
            top += f"& \\multicolumn{{3}}{{c}}{{\\textbf{{Online {t}T (s)}}}} "
        top += "& \\multicolumn{3}{c}{\\textbf{Comm. (MiB)}} \\\\"
        L.append(top)
        sub = "$D$ & Label "
        for _ in present_T:
            sub += "& STL & CST & Spd. "
        sub += "& STL & CST & Save \\\\"
        L.append(sub); L.append("\\midrule")
        for d in present_D:
            for l in present_L:
                row = f"{D_DISP[d]} & {L_DISP[l]} "
                comm = None
                for t in present_T:
                    s = cell.get((d, l, t, "STLPSI")); c = cell.get((d, l, t, "CSTPSI"))
                    if s and c:
                        spd = s[0] / c[0] if c[0] else 0.0
                        row += f"& {b(fmt_t(s[0]), s[0] < c[0])} & {b(fmt_t(c[0]), c[0] < s[0])} & {spd:.1f}$\\times$ "
                        comm = (s[1], c[1])
                    else:
                        row += "& - & - & - "
                if comm:
                    save = (comm[0] - comm[1]) / comm[0] * 100 if comm[0] else 0.0
                    sv = f"{save:.0f}\\%" if save >= 0 else "-"
                    row += f"& {b(fmt_c(comm[0]), comm[0] < comm[1])} & {b(fmt_c(comm[1]), comm[1] < comm[0])} & {sv} "
                else:
                    row += "& - & - & - "
                row += "\\\\"
                L.append(row)
            L.append("\\midrule")
        if L[-1] == "\\midrule":
            L[-1] = "\\bottomrule"
        L.append("\\end{tabular}\\end{table*}")
        open(args.tex, "w").write("\n".join(L) + "\n")
        print(f"[render] LaTeX written to {args.tex}", file=sys.stderr)

    # ---- Markdown ----
    if args.md:
        def mb(x, win): return f"**{x}**" if win else x
        M = ["# Head-to-head: CSTPSI vs. STLPSI baseline (measured)", "",
             "Per-query online time (s) and communication (MiB). Faster time and "
             "lower communication are **bolded**; Spd = STL/CST; Save = CSTPSI "
             "communication saving (`-` = CSTPSI sends more).", ""]
        head = "| D | Label |"; sep = "|---|---|"
        for t in present_T:
            head += f" STL {t}T | CST {t}T | Spd {t}T |"; sep += "---|---|---|"
        head += " Comm STL | Comm CST | Save |"; sep += "---|---|---|"
        M += [head, sep]
        for d in present_D:
            for l in present_L:
                row = f"| {D_DISP[d]} | {L_DISP[l]} |"
                comm = None
                for t in present_T:
                    s = cell.get((d, l, t, "STLPSI")); c = cell.get((d, l, t, "CSTPSI"))
                    if s and c:
                        spd = s[0] / c[0] if c[0] else 0.0
                        row += f" {mb(fmt_t(s[0]), s[0] < c[0])} | {mb(fmt_t(c[0]), c[0] < s[0])} | {spd:.1f}× |"
                        comm = (s[1], c[1])
                    else:
                        row += " - | - | - |"
                if comm:
                    save = (comm[0] - comm[1]) / comm[0] * 100 if comm[0] else 0.0
                    sv = f"{save:.0f}%" if save >= 0 else "-"
                    row += f" {mb(fmt_c(comm[0]), comm[0] < comm[1])} | {mb(fmt_c(comm[1]), comm[1] < comm[0])} | {sv} |"
                else:
                    row += " - | - | - |"
                M.append(row)
        open(args.md, "w").write("\n".join(M) + "\n")
        print(f"[render] Markdown table written to {args.md}", file=sys.stderr)


if __name__ == "__main__":
    main()
